// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CrimeStat struct {
	ID            uuid.UUID
	Neighborhood  string
	TotalCrime    int32
	ViolentCrime  int32
	PropertyCrime int32
	Source        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type HalalRestaurant struct {
	ID        uuid.UUID
	Name      string
	Region    string
	Address   sql.NullString
	Website   string
	Source    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
