// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: restaurants.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createRestaurant = `-- name: CreateRestaurant :exec
INSERT INTO halal_restaurants (id, name, region, address, website, source, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, name, region, address, website, source, created_at, updated_at
`

type CreateRestaurantParams struct {
	Name      string
	Region    string
	Address   sql.NullString
	Website   string
	Source    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) error {
	_, err := q.db.ExecContext(ctx, createRestaurant,
		arg.Name,
		arg.Region,
		arg.Address,
		arg.Website,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
