// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: safety.sql

package database

import (
	"context"
)

const createCrimeStats = `-- name: CreateCrimeStats :one
INSERT INTO crime_stats (id, neighborhood, total_crime, violent_crime, property_crime, source, created_at, updated_at)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
RETURNING id, neighborhood, total_crime, violent_crime, property_crime, source, created_at, updated_at
`

type CreateCrimeStatsParams struct {
	Neighborhood  string
	TotalCrime    int32
	ViolentCrime  int32
	PropertyCrime int32
	Source        string
}

func (q *Queries) CreateCrimeStats(ctx context.Context, arg CreateCrimeStatsParams) (CrimeStat, error) {
	row := q.db.QueryRowContext(ctx, createCrimeStats,
		arg.Neighborhood,
		arg.TotalCrime,
		arg.ViolentCrime,
		arg.PropertyCrime,
		arg.Source,
	)
	var i CrimeStat
	err := row.Scan(
		&i.ID,
		&i.Neighborhood,
		&i.TotalCrime,
		&i.ViolentCrime,
		&i.PropertyCrime,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
